#define SEMICOLON 1
#define ASSIGN 2
#define PLUS 3
#define MINUS 4
#define MULTI 5
#define DIV 6
#define LPAR 7
#define RPAR 8
#define NUMBER 9
#define IDENT 10
#define UNKNOWN 11
#define WHILE 12
#define DONE 13
#define MORE 14
#define LESS 15
#define EQUAL 16
#define MOREOREQ 17
#define LESSOREQ 18 
